name: Post Nouvelair Report Daily

on:
  schedule:
    - cron: '0 10 * * *'  
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the Nouvelair Delay Watch script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          LINKED_API_KEY: ${{ secrets.LINKED_API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          X_API_KEY: ${{secrets.X_API_KEY}}
          X_API_SECRET: ${{secrets.X_API_SECRET}}
          X_ACCESS_TOKEN: ${{secrets.X_ACCESS_TOKEN}}
          X_ACCESS_TOKEN_SECRET: ${{secrets.X_ACCESS_TOKEN_SECRET}}
        run: |
          python main.py    
